env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  # suppress errors for missing 'import React' in files, next.js does that by default
  "react/react-in-jsx-scope": "off",
  # note you must disable the base rule as it can report incorrect errors
  "no-use-before-define": "off",
  "@typescript-eslint/no-use-before-define": ["error"],
  # allow jsx syntax in js files (for next.js project)
  # should add ".ts" if typescript project
  "react/jsx-filename-extension": [1, { "extensions": [".ts".tsx"] }], 
  "quotes": ["error", "double"],
  "react/jsx-one-expression-by-line": "off",
}
settings:
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
