env:
  browser: true
  es2021: true
  node: true
extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "plugin:@next/next/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
rules: {
  # suppress errors for missing 'import React' in files, next.js does that by default
  "react/react-in-jsx-scope": "off",
  # note you must disable the base rule as it can report incorrect errors
  "no-use-before-define": "off",
  "@typescript-eslint/no-use-before-define": ["error"],
  # allow jsx syntax in tsx files (for next.js project)
  "react/jsx-filename-extension": [1, { "extensions": [".tsx", .ts"] }], 
  "quotes": ["error", "double"],
  "react/jsx-one-expression-by-line": "off",
  "max-len": ["error", { "code": 120 }]
}
settings:
  react:
    version: "detect"
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
