channels:
  title: Social
  items:
    - title: GitHub
      to: https://github.com/nicholasjng/
      external: true
    - title: LinkedIn
      to: https://www.linkedin.com/in/nicholas-junge-957082192/
      external: true
    - title: Instagram
      to: https://www.instagram.com/nicholasjunge/
      external: true
    - title: Mail
      to: mailto:nicho.junge@gmail.com
      external: true

sections:
  title: Sections
  items:
    - title: Blog
      to: /blog
      external: False
    - title: Photography
      to: /photography
      external: False
    - title: Mathematics 
      to: /math
      external: False
    - title: Programming
      to: /programming
      external: False
    - title: About me
      to: /about
      external: False
