items:
  - title: Blog
    to: /blog
    activeSelector: /blog
    spanColor: 11
  - title: Photography
    to: /photography
    activeSelector: /photography
    spanColor: 12
  - title: Tags
    to: /tags
    activeSelector: /tags
    spanColor: 13
  - title: About
    to: /about
    activeSelector: /about
    spanColor: 14
