home:
  intro: Latest.
  sectionType: blog
  title: Home
  description: My personal website, made with React and next.js. Contains blog posts, photo reviews, math and tech articles.
blog:
  intro: My Blog.
  sectionType: blog
  title: Blog Posts
  description: All my blog posts on different topics I feel passionate about.
photo:
  intro: Photography.
  sectionType: photography
  title: Photography Blogs and Reviews
  description: All my photography pieces. Includes travel diaries and photography reviews of Leica lenses and cameras.