siteUrl: https://www.nicholasjunge.com
siteRepo: https://github.com/nicholasjng/personal-website

mainAuthor: Nicholas Junge
email: 
  name: nicho.junge
  provider: gmail.com
github: https://github.com/nicholasjng
linkedin: https://www.linkedin.com/in/nicholas-junge/
instagram: https://www.instagram.com/nicholasjunge/

locale: en-US
image: /assets/og/og-default.jpg